spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

products-api:
  host: http://product-service:8080
  path: /api/product

customers-api:
  host: http://customer-service:8081
  path: /api/customer

payment-api:
  host: http://payment-service:8083
  path: /api/payment