spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PRUEBABKCUSCATLAN?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

products-api:
  host: http://localhost:8080
  path: /api/product

customers-api:
  host: http://localhost:8081
  path: /api/customer

payment-api:
  host: http://localhost:8083
  path: /api/payment